---
title: "mnirs: An R Package for Reading, Processing, and Analysing Muscle Near-Infrared Spectroscopy Data"
author:
  - name: "Jem I. Arnold"
    affiliation: ubc_kin
    email: jem.arnold@ubc.ca
    orcid: 0000-0003-3908-9447
affiliations:
  - id: ubc_kin
    name: The University of British Columbia
    department: School of Kinesiology
format:
  docx:
    default
execute:
  echo: true
  message: false
  warning: false
  dpi: 300
  fig-align: center
  out-width: "100%"
# knitr:
#   opts_chunk:
#     collapse: true
#     comment: '#>'
---

::: {.content-visible when-format="docx"}
*ORCID iD:* 0000-0003-3908-9447
:::

```{r setup}
#| code-fold: true
#| code-summary: "Show setup code"

```

<!-- [@Adami2018] -> (Adami and Rossiter 2018) -->
<!-- @Beever2020 -> (Beever et al. (2020)) -->

<!-- Every abstract must contain the following components:

* Sentence stating the study objective, unless given in the title.
* Hypothesis.
* Brief statement of methods, if pertinent.
* Data.
* Summary of the results.
* Statement of the conclusions.
* 2000 characters

Indicate preference for oral presentation (interactive presentation) -->

# Abstract

Muscle near-infrared spectroscopy (mNIRS) is a widely used tool in exercise physiology research, sports science, and clinical rehabilitation for non-invasive assessment of local muscle oxygenation. With the availability of wearable mNIRS devices, data collection has become increasingly accessible. However, data processing and analysis remain inconsistent, with centres often using ad hoc scripts and spreadsheets for signal processing and analysis. 

Such fragmented methods limit reproducibility and hold back standardisation in the field. Here we introduce `{mnirs}`, an open-source R package developed specifically for mNIRS data. `{mnirs}` provides a standardised, reproducible pipeline for reading files, cleaning, filtering, transforming, extracting, and visualising time-series data from mNIRS devices. The package website is at: https://jemarnold.github.io/mnirs/

Alongside the flexible R package, a basic no-code workflow is available as a free online app available at: https://jemarnold-mnirs-app.share.connect.posit.cloud/. This tool is designed for researchers, practitioners, and aspiring NIRS users with minimal coding experience, emphasising accessibility, reproducibility, and transparent processing decisions.

# Objective

The objective of this presentation is to introduce a new data-processing tool to the mNIRS community through an interactive demonstration of common processing tasks, including:

- Deoxygenation and reoxygenation kinetics during incremental exercise.
- Microvascular responsiveness with slope- and time-based kinetics after a resting vascular occlusion.
- Muscle oxidative capacity assessment with repeated occlusions after an exercise stimulus, using monoexponential curve fitting.

# Requested presentation Format

We would prefer an oral presentation or a digital poster format to interactively demonstrate `{mnirs}` R package and app capabilities. If possible, an opportunity for conference attendees to engage with the online app with their own data and provide feedback to the app author would be valuable. This could be outside of formally scheduled presentations.